import type { Block } from '../types';

export const SPECIALITES = [
  { value: 'physique-chimie', label: 'Physique-Chimie' },
  { value: 'svt', label: 'SVT' },
  { value: 'maths', label: 'Mathématiques' },
  { value: 'biologie-ecologie', label: 'Biologie-écologie' },
  { value: 'hlp', label: 'Humanités, littérature et philosophie' },
  { value: 'hggsp', label: 'HGGSP' },
  { value: 'histoire-arts', label: 'Histoire des arts' },
  { value: 'llce-anglais', label: 'LLCE Anglais' },
  { value: 'ses', label: 'SES' },
  { value: 'autre', label: 'Autre' },
];

export const LICENCES_LAS = [
  { value: 'droit', label: 'Droit' },
  { value: 'biologie', label: 'Biologie' },
  { value: 'chimie', label: 'Chimie' },
  { value: 'physique', label: 'Physique' },
  { value: 'psychologie', label: 'Psychologie' },
  { value: 'staps', label: 'STAPS' },
  { value: 'economie', label: 'Économie' },
  { value: 'histoire', label: 'Histoire' },
  { value: 'lettres', label: 'Lettres' },
  { value: 'philosophie', label: 'Philosophie' },
  { value: 'sociologie', label: 'Sociologie' },
  { value: 'autre', label: 'Autre' },
];

export const INTERET_PREPA = [
  { value: 'oui-definitivement', label: 'Oui, définitivement' },
  { value: 'oui-peut-etre', label: 'Oui, peut-être' },
  { value: 'non', label: 'Non' },
  { value: 'je-ne-sais-pas', label: 'Je ne sais pas encore' },
];

export const UNIVERSITES = [
  { value: 'amiens', label: 'Amiens' },
  { value: 'angers', label: 'Angers' },
  { value: 'antilles', label: 'Antilles (Martinique, Guadeloupe)' },
  { value: 'besancon', label: 'Besançon' },
  { value: 'bordeaux', label: 'Bordeaux' },
  { value: 'brest', label: 'Brest' },
  { value: 'caen', label: 'Caen' },
  { value: 'clermont-ferrand', label: 'Clermont-Ferrand' },
  { value: 'dijon', label: 'Dijon' },
  { value: 'grenoble', label: 'Grenoble' },
  { value: 'la-reunion', label: 'La Réunion' },
  { value: 'lille-etat', label: 'Lille État' },
  { value: 'limoges', label: 'Limoges' },
  { value: 'lyon', label: 'Lyon' },
  { value: 'marseille-aix', label: 'Marseille - Aix' },
  { value: 'montpellier', label: 'Montpellier' },
  { value: 'nancy', label: 'Lorraine (Nancy)' },
  { value: 'nantes', label: 'Nantes' },
  { value: 'nice', label: 'Nice' },
  { value: 'paris-cite', label: 'Ile de France - Paris Cité' },
  { value: 'paris-saclay', label: 'Ile de France - Saclay' },
  { value: 'poitiers', label: 'Poitiers' },
  { value: 'reims', label: 'Reims' },
  { value: 'rennes', label: 'Rennes' },
  { value: 'rouen', label: 'Rouen' },
  { value: 'saint-etienne', label: 'Saint-Étienne' },
  { value: 'sorbonne-nord', label: 'Ile de France - Sorbonne Nord' },
  { value: 'sorbonne', label: 'Ile de France - Sorbonne' },
  { value: 'strasbourg', label: 'Strasbourg' },
  { value: 'toulouse', label: 'Toulouse' },
  { value: 'tours', label: 'Tours' },
  { value: 'creteil', label: 'Ile de France - Créteil (UPEC)' },
  { value: 'uvsq', label: 'Versailles - Saint-Quentin (UVSQ)' },
];

export const blocks: Block[] = [
  {
    id: 1,
    title: 'Ton profil',
    shortTitle: 'Profil',
    questions: [
      {
        id: 'parcours',
        type: 'dropdown',
        label: 'Quel parcours vises-tu ?',
        required: true,
        options: [
          { value: 'PASS', label: 'PASS (Parcours Accès Santé Spécifique)' },
          { value: 'LAS', label: 'LAS (Licence Accès Santé)' },
        ],
      },
      {
        id: 'university',
        type: 'dropdown',
        label: 'Dans quelle université ?',
        required: true,
        options: UNIVERSITES,
      },
      {
        id: 'sousVoeuxMultiple',
        type: 'boolean',
        label: 'Combien de sous-vœux PASS fais-tu ?',
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
        falseLabel: 'Un seul',
        trueLabel: 'Plusieurs',
      },
      {
        id: 'sousVoeuxDetail',
        type: 'text',
        label: 'Quel sous-vœu ?',
        dynamicLabel: { field: 'sousVoeuxMultiple', value: true, label: 'Quels sous-vœux ?' },
        placeholder: 'Exemple : Droit',
        dynamicPlaceholder: { field: 'sousVoeuxMultiple', value: true, placeholder: 'Exemple : Droit, Philosophie, Économie...' },
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
      },
      {
        id: 'licenceMajeure',
        type: 'dropdown',
        label: 'Quelle est ta licence majeure ?',
        required: true,
        options: LICENCES_LAS,
        condition: { field: 'parcours', value: 'LAS' },
      },
    ],
  },
  {
    id: 2,
    title: 'Ton parcours',
    shortTitle: 'Parcours',
    questions: [
      {
        id: 'motivationLicence',
        type: 'text',
        label: 'Pourquoi as-tu choisi cette licence ?',
        placeholder: 'Depuis mon stage en cabinet d\'avocat, je suis fasciné par les questions de responsabilité médicale. Le droit me permettra de comprendre les enjeux éthiques qui encadrent la médecine...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
      {
        id: 'specialite1',
        type: 'dropdown',
        label: 'Spécialité 1',
        required: true,
        options: SPECIALITES,
        inlineWith: 'moyenne1',
        excludeFrom: 'specialite2',
      },
      {
        id: 'moyenne1',
        type: 'number',
        label: 'Moyenne',
        required: true,
        min: 0,
        max: 20,
      },
      {
        id: 'specialite2',
        type: 'dropdown',
        label: 'Spécialité 2',
        required: true,
        options: SPECIALITES,
        inlineWith: 'moyenne2',
        excludeFrom: 'specialite1',
      },
      {
        id: 'moyenne2',
        type: 'number',
        label: 'Moyenne',
        required: true,
        min: 0,
        max: 20,
      },
      // PASS - exempleQualite
      {
        id: 'exempleQualite',
        type: 'text',
        label: 'Quelle qualité te permettra de réussir en médecine ? Prouve-le avec un exemple concret.',
        placeholder: 'Ma rigueur : en Terminale, j\'ai mis en place un planning de révision strict que j\'ai tenu 6 mois, ce qui m\'a permis d\'améliorer ma moyenne de 3 points...',
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
      },
      // LAS - exempleQualite
      {
        id: 'exempleQualiteLAS',
        type: 'text',
        label: 'Quelle qualité te permettra de réussir ta double licence ? Prouve-le avec un exemple concret.',
        placeholder: 'Ma capacité d\'organisation : en Terminale, je gérais mes cours, 8h de tennis par semaine et du bénévolat. Cette rigueur me permettra de mener de front ma licence et l\'option santé...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
      // PASS - projetSante
      {
        id: 'projetSante',
        type: 'text',
        label: 'As-tu réalisé un projet ou une expérience en lien avec la santé (stage, TPE, bénévolat...) ? Comment cela a-t-il confirmé ton choix ?',
        placeholder: 'Mon stage d\'observation de 3 jours en cabinet de médecine générale m\'a permis de voir la relation médecin-patient au quotidien et de confirmer que c\'est cette proximité humaine qui me motive...',
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
      },
      // LAS - projetSante
      {
        id: 'projetSanteLAS',
        type: 'text',
        label: 'As-tu réalisé un projet ou une expérience en lien avec ta licence ou la santé ? Comment cela a-t-il confirmé ton choix de double parcours ?',
        placeholder: 'Mon stage en cabinet d\'avocat spécialisé en droit médical m\'a montré comment le droit et la santé se complètent. Cela a confirmé mon envie de combiner ces deux disciplines via la LAS Droit...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
    ],
  },
  {
    id: 3,
    title: 'Projet & Motivation',
    shortTitle: 'Projet',
    questions: [
      {
        id: 'motivationMedecine',
        type: 'text',
        label: 'Quelles sont tes raisons profondes de vouloir devenir médecin ?',
        placeholder: 'À 12 ans, j\'ai accompagné ma grand-mère à ses rendez-vous médicaux. Observer le médecin prendre le temps de lui expliquer sa maladie m\'a donné envie de créer ce même lien de confiance...',
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
      },
      {
        id: 'mineureCoherence',
        type: 'text',
        label: 'En quoi ta ou tes mineures sont-elles un choix cohérent avec ton projet médical ?',
        placeholder: 'J\'ai choisi la mineure Droit de la santé car elle me permettra de comprendre les enjeux éthiques et juridiques de la pratique médicale...',
        required: true,
        condition: { field: 'parcours', value: 'PASS' },
      },
      {
        id: 'motivationSante',
        type: 'text',
        label: 'Pourquoi veux-tu accéder aux études de santé ?',
        placeholder: 'L\'accompagnement de mon grand-père pendant sa maladie m\'a fait découvrir l\'importance du lien soignant-patient. Je veux exercer un métier où je peux avoir cet impact humain au quotidien...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
      {
        id: 'lienLicenceSante',
        type: 'text',
        label: 'Quel lien fais-tu entre ta licence et la santé ?',
        placeholder: 'Ma licence de Droit me donnera une compréhension des enjeux juridiques et éthiques de la médecine. Ces compétences seront précieuses pour accompagner mes patients dans leurs droits...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
      {
        id: 'activiteIntensiveLAS',
        type: 'text',
        label: 'Pratiques-tu une activité intensive (sport, musique...) ? Si oui, décris-la et ce qu\'elle t\'apporte.',
        placeholder: 'Je fais du tennis en compétition depuis 8 ans (niveau régional). Cette pratique m\'a appris la persévérance et la gestion du stress, des qualités essentielles pour gérer ma double licence...',
        required: true,
        condition: { field: 'parcours', value: 'LAS' },
      },
      {
        id: 'engagementConcret',
        type: 'text',
        label: 'Décris un engagement extra-scolaire concret et la qualité qu\'il a développée chez toi.',
        placeholder: 'Bénévole aux Restos du Cœur depuis 2 ans, j\'ai développé mon écoute et ma capacité à m\'adapter à des personnes en difficulté...',
        required: true,
      },
    ],
  },
  {
    id: 4,
    title: 'La faculté',
    shortTitle: 'Faculté',
    questions: [
      {
        id: 'jpo',
        type: 'boolean',
        label: 'As-tu participé à une JPO de cette université ?',
        required: true,
      },
      {
        id: 'jpoRetenu',
        type: 'text',
        label: 'Qu\'as-tu retenu de cette JPO ?',
        placeholder: 'J\'ai discuté avec un étudiant en 2ème année qui m\'a expliqué le système de tutorat. Son enthousiasme et ses conseils m\'ont convaincu que cette fac accompagne vraiment ses étudiants...',
        required: true,
        condition: { field: 'jpo', value: true },
      },
      {
        id: 'attractionFac',
        type: 'text',
        label: 'Qu\'est-ce qui fait de cette faculté l\'environnement idéal pour ta réussite ?',
        placeholder: 'Le tutorat organisé par les étudiants de 2ème année me permettra d\'avoir un accompagnement personnalisé et des conseils de méthodologie adaptés au programme de cette faculté...',
        required: true,
      },
    ],
  },
];

export const ENCOURAGING_MESSAGES = [
  'Super, on avance bien !',
  'Parfait, continue comme ça !',
  'Excellent, tu y es presque !',
  'Génial, encore quelques questions !',
  'Top ! La suite maintenant.',
];

export function getRandomEncouragingMessage(): string {
  return ENCOURAGING_MESSAGES[Math.floor(Math.random() * ENCOURAGING_MESSAGES.length)];
}
